[package]
name = "kaleidoscope-algo"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.51" }
clap-num = "1.2.0"
clap_derive = "4.5.49"
rand = "0.9.2"
serde_json = "1.0.145"
